---
compose_engine: docker
compose_project_src: "{{ inventory_dir }}/files/compose"
compose_project_dest: /opt/compose
compose_pull: policy
compose_build: policy
compose_recreate: auto
compose_remove_orphans: false
compose_project_name: "{{ compose_project_dest | basename }}"
additional_folders: []
additional_folders_owner: root
additional_folders_group: root
