---
- name: Restart compose project
  ansible.builtin.systemd:
    name: compose-{{ compose_project_dest | basename }}
    state: restarted

- name: Reload systemd compose unit
  ansible.builtin.systemd:
    daemon_reload: true
