# start prosody
upstream prosody_xmpp {
   	server {{ prosody_backend | default('10.255.2.27') }}:5222;
}

# xmpp client connections
server {
	listen 5222; # Listen for incoming client connections
	# listen 5223; # Listen for incoming client connections
	# listen 5222 ssl; # Listen for incoming client connections
	proxy_pass prosody_xmpp;
	# proxy_protocol on;
{% if acme_enabled | default(true) %}
	ssl_certificate $acme_cert_{{ acme_client_name | default('letsencrypt') }};
	ssl_certificate_key $acme_cert_key_{{ acme_client_name | default('letsencrypt') }};
{% else %}
	ssl_certificate "/etc/letsencrypt/live/{{ xmpp_domain }}/fullchain.pem";
        ssl_certificate_key "/etc/letsencrypt/live/{{ xmpp_domain }}/privkey.pem";
{% endif %}
	ssl_certificate_cache max=1000 inactive=20s valid=1m;
}

upstream prosody_s2s {
   server {{ prosody_backend | default('10.255.2.27') }}:5269;
}

# xmpp s2s
server {
	listen 5269;
	proxy_pass prosody_s2s;
	# proxy_protocol on;
{% if acme_enabled | default(true) %}
	ssl_certificate $acme_cert_{{ acme_client_name | default('letsencrypt') }};
	ssl_certificate_key $acme_cert_key_{{ acme_client_name | default('letsencrypt') }};
{% else %}
	ssl_certificate "/etc/letsencrypt/live/{{ xmpp_domain }}/fullchain.pem";
        ssl_certificate_key "/etc/letsencrypt/live/{{ xmpp_domain }}/privkey.pem";
{% endif %}
	ssl_certificate_cache max=1000 inactive=20s valid=1m;
}
# end prosody
