---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    CF_API_TOKEN: AgA9fW87oBWP6tMo0n6UVMYVUjEN3ZrJ2upBrmeTpwcTtSYNWWFLnRFat5fBn9jlcgMjrTKqf8EyUvbf/esqpFkUHcwag8+wqgundoquh9EDw6Q3jOYL44o1LWumZ9GSNAY7uNiqkiJOcTg/zagjmGhTgm2kJjtNKbo2j+lH+KuH7Y5WuPHoGkhO2Fi0D889VdRkN2z6GouWbOAjf3/XAcV9TB5UVxdyAfObrHs+HBIXXYRSdsMYB9R0wq2eCw3w7WTPsKiX9M4P7l9aoCtVLllvtkpvPcQyIHyC5B2yDkirT933f84xBbySVbV1LqL6py5PiPcG2uTW+SgY8DR8jhWiueJW31iyG7sG6/MH42k9+3UCo6ByVrhsx5lT2NxlAzurzF9KiITj7kQDZkU7Qc/n7VvPn9gd+5o5F7Xlu5eq0f41kIWDupy7JI4SloNgQy5ImTawmWmnSGMlyEqbWmaTwe3WbfvfYOk7hG2VeJO5ONgD0JIbMP06Od5PyfrWHn0w7hnyBCME/TTU7v/MbMfnhRpfrEumn4l5S75q5ymrmMkBKoWZhpLypQXLG5SN70ZFD7Tszhw8g9LwIy6pQsQRdgHesN27N7CgWkNR1L4ejNjsO4YKlrMAxR5xrsEO8ABHFYcxHoJSP2RiJRFB5lqn02iruXhwaqikpEtw0u2/gebRY4VotHrgBs0CD+Z38zdsu465cmseO5AtkmN6wkgj1Y6SV3kvn0c/CweLnKFCzACyDO1MGg/waWu9yg9CCi5ZcsdhMw==
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
