image:
  repository: vaultwarden/server
  tag: "1.37.1-alpine"
  pullPolicy: IfNotPresent

replicaCount: 1

persistence:
  size: 10Gi
  storageClassName: nfs

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: vw.rcpassos.me
      paths:
        - path: /
          pathType: Prefix

service:
  port: 80

resources:
  limits:
    memory: 4196Mi
  requests:
    cpu: 100m
    memory: 2560Mi

env:
  TZ: "America/Sao_Paulo"
  DOMAIN: "https://vw.rcpassos.me"
