apiVersion: v2
name: kubewarden
description: "kubewarden"
version: 5.14.1
dependencies:
  - name: kubewarden-controller
    # WARN: rember to check the CRD version when upgrading.
    # it is defined in the Makefile
    version: 5.14.1
    repository: https://charts.kubewarden.io
