---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: "{{ apt_upgrade_type }}"
  register: _apt_upgrade

- name: Autoremove orphaned packages
  ansible.builtin.apt:
    autoremove: true
  when: apt_autoremove | bool

- name: Clean apt cache
  ansible.builtin.command: apt-get autoclean
  changed_when: false
  when: apt_autoclean | bool
