---
- name: Deploy gitlab_runner via Docker Compose
  hosts: gitlab_runner
  become: true
  roles:
    - role: compose
      vars:
        compose_engine: docker
        compose_project_src: "{{ inventory_dir }}/../gitlab_runner"
        compose_project_dest: /opt/gitlab_runner
