---
- name: Deploy Prosody XMPP server
  hosts: prosody
  become: true

  roles:
    - prosody
    - role: alloy
      vars:
        service_name: prosody
        local_log_files:
          - path: "/var/log/prosody/prosody.log"
            job: "prosody"
            service_name: "prosody"
        enable_logfile: true
        compose_engine: podman
        log_instance_name: "prosody-server"
        # external_labels:
        #   env: "production"
        #   region: "brazil"
        enable_port: true
        enable_systemd_logs: true
        systemd_logs_service:
          - service: "container-matridge.service"
            name: "matridge"
          - service: "biboumi.service"
            name: "biboumi"
