---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lgtm-loki-s3
  namespace: observability
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAHr6LYfZg5KVvVF5XbEAXFrDnb5MNKQP4j+p8zXWRvjrIXV7LkJHraDY1gYNRRsu36/7hoPRqAs4GSVwb7Go9jfYbz8yeR9NzFklENYq0IEFGuuBEFrtcnRqcaSLfUUnl7Vmal13OaIVLuRPYd66zHAyF1yMM91Evz1s3NJCauoKGx+2zrwtnze5DyP/973RhSmvhJneltlYXG7+25wgpi1U06Td+P3RsR8wXNkYXWAr5MyVbuFIBEW/v+S8aTpr928t7RR4uLhcJbMp+9NoQicIc4L7a6F/gzFqV1TSD5Fyt4M2ROoU5xAuLYbmYedm+lwSPoWna81OjVqhZQnYH+rd43qTe6KL+DxWLRqHhwbsy/t6aCp0qgb/UKwPxW+HI925ENXpa72+WagaEvug7JMoivOuHr4otMDp0gC8pn8Sqejs9mnpUGYUeoX+VKWYMl/5l5SYgoHXU302erp5P3na2U2s0pXR9MALd5duY8WYaIbNydgoGSDa5AHmzEockFRgIaYtS8quCECThHeTAXFmRiFnq7/A1qymvBo4RuhAZB4qfu3ePkGuDqSNJS1JR0Vz5FbepuJxT8Tx4rtzsK6BR5ADr39ErapM++maYnPQQuuy2ETopM5nrSFbomvgC7gV6AOpKmdC5UDfBJdCCjn6Jk/MQLO9YSKpXX28y+5JWmoU1CIIfCn7II/PhlDaKzecS+
    AWS_SECRET_ACCESS_KEY: AgBXoPBD57bplzXabCBca9j26bBO5a3js8Zcsqa/pMZi9h+NApt8/Djw+JtDQ1N/5dyTMLuKoydGUcJKoEXqnVrigu4HDAloMf4dZzLhTWRomyDRg3rgglIkc0t84IM1uwZJ3hotaUJEJe/8v2CIpcZVwc1lGiUseaZV52l1Jv00RmvzRSgGBFrgUX2AeQf8sY3uCRH+s0tNOKgB0aAJeH/i/d51EAcnS1HY998M3yxbkuLowhebwBpZI/UEYFOphSNFDZnNTDCjITKLl4pk7V7A4FUFIGF7MUTUPPIPsItXGideVRGRDd2ieOUCI9G8Rfhb1iDwQqHKnr9xaGP+2BiXf+GBzDzkx+6emOFKGEI3Rl0j+GgLz8SSAdsFvp8ZZLiTu6PcBqHQ+WwPhtPRC2zb2aQndmn8JAaFvMd1FRhs5bpSIYWQ2MGXDKA76LrGAfRCZ78eHDjJK/wjnrKySKEQKe5djfnmGoRUMeEuIYbmDDC1/CVomSl0/uz++31vnl3lVROaS2O8GOiKR6msfyoQKL6Tsj0KXqDyTjT9NNXldQdSXzQvjlZm1L6puFN9zI5WZAp9UAoICnP+LbKyc5mmE4xOfrHTCi2ebzpI3A8tWek+ndMfgp50PrnDBhzZaz+Az7/aSRz1khFO9ZSqde+wgBv18YepPsjUGYxxMo1q/j+7iH0zed7IIl0vEssJNRoSuZGmQHg8SvR9ElWcSbz7NDfchJWGBAHJ
  template:
    metadata:
      name: lgtm-loki-s3
      namespace: observability
